# Generated by Django 3.2.15 on 2022-10-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='img2',
            new_name='img1',
        ),
    ]
